- name: Install nginx
  hosts: web
  become: yes #root user
  tasks:
   - name: Install nginx package 
     ansible.builtin.package:
      name: nginx
      state: present
      
   - name: Start the Nginx service and ensure it runs on boot
     ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
        