- name: play level variabless
  hosts: web
  vars_files:
   - couse.yaml
  
  tasks:
   - name: Print variabless
     vars: 
      course: "Ansible"
     ansible.builtin.debug:
      msg: "course is: {{ course }}, trainer is: {{ trainer }}"