- name: play level variabless
  hosts: web
  vars: 
   course: "Devops"
   duaration: "140hrs"
   trainer: "Shiva"
  tasks:
   - name: Print variabless
     vars: 
      course: "Ansible"
     ansible.builtin.debug:
      msg: "course is: {{ course }}, trainer is: {{ trainer }}"