- name: print username and password
  hosts: web
  vars_promt: 
   - name: username
     promt: please enter username
     private: false

   - name: password
     promt: please enter password
     private: True

  tasks:
   - name: print info
     ansible.builtin.debug:
      msg: "username is: {{ username }}, password is: {{ password }}"  