- name: variable prefence
  hosts: web
  vars:
   Name: "Ansible from Mahesh"
  vars_files:
   - couse.yaml 

  vars_prompt: 
   - name: Name
     prompt: please enter name
     private: false
  tasks:
   - name: print name
     vars: 
      Name: "Ansible from yogita"
      ansible.builtin.debug:
       msg: "Hi {{ Name }}"
